#!/usr/bin/env python

Import('env')
Import('env_modules')

env_wmf = env_modules.Clone()

env_wmf.add_source_files(env.modules_sources, "*.cpp")

MSLIBS = ['mfuuid', 'evr', 'mfplat', 'mf', 'mfreadwrite']

env_wmf.Append(LINKFLAGS=[p + env_wmf["LIBSUFFIX"] for p in MSLIBS])