#!/usr/bin/env python
Import('env')

env.add_source_files(env.modules_sources,"*.cpp")

# doing dynamic linking cause it's easier to get started... :(

# add the flags
env.Append(CPPFLAGS=["-lopencv_core"])
env.Append(CPPFLAGS=["-lopencv_imgproc"])
env.Append(CPPFLAGS=["-lopencv_imgcodecs"])
env.Append(CPPFLAGS=["-lopencv_highgui"])
env.Append(CPPFLAGS=["-pthread"])

# link the libs
env.Append(LINKFLAGS=["-lopencv_core"])
env.Append(LINKFLAGS=["-lopencv_imgproc"])
env.Append(LINKFLAGS=["-lopencv_imgcodecs"])
env.Append(LINKFLAGS=["-lopencv_highgui"])
env.Append(LINKFLAGS=["-pthread"])